version: '3'
services:
  server:
    build: ./server
    command: pipenv run flask run --host 0.0.0.0
    volumes:
      - './server:/usr/src/app'
    ports:
      - '5000:5000'
  client:
    build: .
    command: yarn serve
    volumes:
      - '.:/usr/src/app'
    ports:
      - '8080:8080'
